export const dummyData = [
  {
    id: "Harry-053",
    name: "Harry Davis",
    gender: "Male",
    phoneNumber: "+91 2481133053",
    email: "harry.davis@example.com",
    accountType: "Personal",
    // image: "https://randomuser.me/api/portraits/male/77.jpg",
  },
  {
    id: "Lara-525",
    name: "Lara Adams",
    gender: "Female",
    phoneNumber: "+91 4884017525",
    email: "lara.adams@example.com",
    accountType: "Business",
    // image: "https://randomuser.me/api/portraits/female/89.jpg",
  },
  {
    id: "Frank-336",
    name: "Frank Brown",
    gender: "Male",
    phoneNumber: "+91 4264084336",
    email: "frank.brown@example.com",
    accountType: "Personal",
    // image: "https://randomuser.me/api/portraits/male/46.jpg",
  },
  {
    id: "Julie-798",
    name: "Julie Adams",
    gender: "Female",
    phoneNumber: "+91 4923573798",
    email: "Julie.adams@example.com",
    accountType: "Business",
    // image: "https://randomuser.me/api/portraits/female/6.jpg",
  },
  {
    id: "Chris-753",
    name: "Chris Harris",
    gender: "Male",
    phoneNumber: "+91 3751597753",
    email: "chris.harris@example.com",
    accountType: "Personal",
    // image: "https://randomuser.me/api/portraits/male/72.jpg",
  },
  {
    id: "Ben-587",
    name: "Ben Adams",
    gender: "Male",
    phoneNumber: "+91 4758639587",
    email: "ben.adams@example.com",
    accountType: "Personal",
    // image: "https://randomuser.me/api/portraits/male/21.jpg",
  },
  {
    id: "Ivan-422",
    name: "Ivan Brown",
    gender: "Male",
    phoneNumber: "+91 7190368422",
    email: "ivan.brown@example.com",
    accountType: "Business",
    // image: "https://randomuser.me/api/portraits/male/5.jpg",
  },
  {
    id: "Ben-008",
    name: "Ben Harris",
    gender: "Male",
    phoneNumber: "+91 4426700008",
    email: "ben.harris@example.com",
    accountType: "Business",
    // image: "https://randomuser.me/api/portraits/male/12.jpg",
  },
  {
    id: "rachel-013",
    name: "Rachel Green",
    gender: "Female",
    phoneNumber: "+91 5660636013",
    email: "rachel.green@example.com",
    accountType: "Business",
    // image: "https://randomuser.me/api/portraits/female/71.jpg",
  },
  {
    id: "Ivan-352",
    name: "Ivan Johnson",
    gender: "Male",
    phoneNumber: "+91 3558641352",
    email: "ivan.johnson@example.com",
    accountType: "Personal",
    // image: "https://randomuser.me/api/portraits/male/88.jpg",
  },
];
